import { Response } from "express";
import { z } from "zod";
import prisma from "../lib/prisma";
import { AuthRequest } from "../middleware/auth.middleware";

const noteInput = z.object({ title: z.string().trim().min(1).max(250), content: z.string().max(20_000).optional(), folderId: z.string().uuid().nullable().optional() });
async function validFolder(folderId: string | null | undefined, userId: string) { return !folderId || !!await prisma.folder.findFirst({ where: { id: folderId, userId }, select: { id: true } }); }

export async function listNotes(req: AuthRequest, res: Response) { const userId = req.user?.userId; if (!userId) return res.status(401).json({ error: "Unauthorized" }); return res.json(await prisma.note.findMany({ where: { userId }, orderBy: { updatedAt: "desc" } })); }
export async function createNote(req: AuthRequest, res: Response) { try { const userId = req.user?.userId; if (!userId) return res.status(401).json({ error: "Unauthorized" }); const parsed = noteInput.safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0].message }); if (!await validFolder(parsed.data.folderId, userId)) return res.status(404).json({ error: "Project not found" }); return res.status(201).json(await prisma.note.create({ data: { ...parsed.data, userId } })); } catch { return res.status(500).json({ error: "Could not create note" }); } }
export async function updateNote(req: AuthRequest, res: Response) { try { const userId = req.user?.userId; if (!userId) return res.status(401).json({ error: "Unauthorized" }); const parsed = noteInput.partial().safeParse(req.body); if (!parsed.success) return res.status(400).json({ error: parsed.error.issues[0].message }); const note = await prisma.note.findFirst({ where: { id: req.params.id, userId }, select: { id: true } }); if (!note) return res.status(404).json({ error: "Note not found" }); if (!await validFolder(parsed.data.folderId, userId)) return res.status(404).json({ error: "Project not found" }); return res.json(await prisma.note.update({ where: { id: note.id }, data: parsed.data })); } catch { return res.status(500).json({ error: "Could not update note" }); } }
export async function deleteNote(req: AuthRequest, res: Response) { const userId = req.user?.userId; if (!userId) return res.status(401).json({ error: "Unauthorized" }); const note = await prisma.note.findFirst({ where: { id: req.params.id, userId }, select: { id: true } }); if (!note) return res.status(404).json({ error: "Note not found" }); await prisma.note.delete({ where: { id: note.id } }); return res.json({ message: "Note deleted" }); }
